---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgB5stcEJHFiyUyUuE+NGTffGTbAKhlHWutqVSHJTnL+OoT4YjvKunhNMWCoJghiuWJlsWbmmkqCljYoJAIuET02s5QQaV7lLVt5UfGX9Ga7zgIzvu0JDjtSrd+Rxg8KUl6byPVdNooIJrhmAW7MjQE+rwqnuo6Whl7c2sckKxQIgixkFK6ytEh0ECdKNAOyxwydg/cIl0VhL4fZeY6bAdWSYLVjit3DqE8LcV9hWdN6AWFK2hWRhCS26gM0L5+NUremWhUZ8iLiR/Q4XsaEdCxvP/21EOIiF81/skD1mdngdoJnGp/jlr5a5mTSKPJFvxZT8bwcJSE9xP1u1XY3y4SV8OyPQTDIxA6olLgiwyb8Qo2hnfXk+LHKytuwUOPeqUmW3xsFX/pwxDO+6NkWviD9e9NrKcSM18J4yeHn91e+JSMq1JI5Km5x3kv0QRQIJ/zyGB5PJktqACuERGDpnCu2XXZtdJhGIof5nJiCdDI0rp1SpTwAgIXK8ZVWUaBI9yeQmHZczKdA6W8xF0yCncjw7vBqoibNn6rw/iomVUggHD6Xel6GcdK6uva6eJwpAVxcUWe8F/+nfjjPM690uGI0qwKIAliN5zYwa9c+Keuc8Rn1aLWNP/0zkXJ3chdmPxQC4nrLv5BivONziDQ8L0OdrqYXJOgzhedTou1B5GH4xHQaicwrJHIRU3uZTwiFRvJkmXop/RTipYOZHg==
    username: AgAMUrcJkdAeSYqNLkaIXlXoaIjsTeEUc3rJ/z/E44gQLOsndKuzLH13BUkH4lTS29cuSgJro9j7oPpeibqK4qI/X4zr2jmnmCWSC9I4x/77HDdpg2WB8nbbkpZTjZzA40vXKlLFmaAoRiEekW6ytqHrr6VoA5nyHQ/kPGyEBv4LLTNp4XPA9eKYlSDbe2a/7O0zzALexmTxhlFQ5xwEMCMgWUfFg2EhjZdrzrLCXJabQ9N0X/w4+000t5nNPgdT4KRdgBVkR7PlD3EEcYq9/X6E/JB2kov+BA6J7DRg02oyOe/H9ZXwpB/sNB8PjOoZoO5Sv3JyQL3HJi0js0cdyXPHEj/wXHKJkwERGI0R38AsQKEedF8SmKylK6jC9hxXjDNBlrWdcrvhwVnTtReji/EJNZC+gtndk61yy1u8QLlsV6FL7bvjZ9KHgE14bDitcQe7otciyEMg2oap+iMgguloWsEwGsGopjgWxeO4M0v63YWAq268sA2/53uDDFY/h02jL5HUxLy9C5RduRN1H0Opq3xw9uyOoZ+VuBu6aJedOFr0eVyObniQq1OH9NXd4H+PEOF1cof+LhXYS9A1az9j188Dp4evre9mZpPNn/1UeEGNDX0eDL3RJNNM/PyiRVpkC6Pq2QCVfFqSmytHeNLVIAYK6lPRonVJH61qcWJ56zPICjiZxAnuz8+441Muu0WiWF1Wzg==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
