---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgB76azKAn8y6UzNEF9hU3TLyz2bRBlXG2s2oN19vWDy0mA+/NzXfrcJyL1ArnM65KIYcGEhoC4ZFq8CrG1/NRUX9cQGdfKyAW1i0fQNso60BrXglcTDAmRpv6yIsJXdJHYPvNJOc8KG1wY/LHrczcEnCD9g9Zw3fsBQi0AWT9ab9fSNDoxEK/+e5O2vav+PcDxCUz63EQBnMmsWm+ldlgWksKxRZ49tTqaFlzomUlzjLkLpj1BPjlGxHiHLKk7bB08NM/+xuJ98r+D0vtByn/Xptz6qj3PijUNg9rSo1v6unxiqZuasD2OTyJS6xKtK8tB0mXk/dMhm6RTr7iBXy26RsNU/f4jDBA7bfiFY7RtJ9H6l9gked25N4JQMvLZLAjOnsm7ObyrQpnBGcC9Qx+SNudeRRbcYTmt4HEfecfL7xEVk+PabNe6GY4rJAcnzqw+UoJWhMP5nqL8kZoOC+OOjnHP0yI1H+/lZmvA9EZ66OrZWmxUeb0lsVCKA7b42E6qSvb5hgk+ipsnC70Z6TJO+tfiNe49Sx1M12BIbsmxc6VU1D0kmrC0MiYaLX7k9EhN74o4q8PnQVDgC9/ePKWcASAnV3WR6stT2dHc+Q6KqphIgQn+Mu03GNyROB4WTUlOSQi2UtKLLGOO2XA7V2l5VMpp0tWIWpHQ9AV/0Wd9m/kHDyb5bP+eABrilI2SRB5MitVkNbUamw1pWxg==
    username: AgCBBWQywGjDqCl0NRjNoxKBhgoato6RowP6I/2mGYRSgGwk/gZyXlztxSp0PdvDjtHl0YgcsSq8yGLIN0Myn7Ghky49UmZjemdqpRBHpeWF0SLe8G8iveQn5OzVFelPqZPzDGlSe/VsrRJX73Rp2FdDYqL+p/7sXBgJYwUwI6e7/Os511MfWq24fdv0yMousxVJwyo1NORRKwPmthgLzTiLGvsZ/qO/bn58Cbt4navuT0Fa+mgBoLMxKtb9vxVjPchjsdbWjUHWyZOtNPp4clUuf2urOJLUOPNGNt1yAoLUpp5Vdl6v/YQja/Jb5WaDEcOE75cRg5Cw5HUOUhf1EjSYm/pg5cXfkVtJWoqZ4cOUUHvsHRIRhBTQky8ptprqjEp9r0XX+FqIHbZE+WcJ79jD8jFQjbjQVFbVlbIi1bKy+H8y/MHfY2fPVP0tp3DvGOeSkX3d9kjepTzNE0wnfhNM/2Kfwrec0a4Xa6e/nQE7bQVi69WusPtb7VoCAcDFGQy3b8f5nlaNATEUxPE9FkwYPn6R3BLZIweMs7v3t8I9YCP5Tjr94T8ShHiplpFKtOv1HGynNpp72Au/S+2ubFNd97Gcx9xSZ6kw7dZ5DsbmEaefIUwzU0Nea41w5+ONRikO9YcTVdYvGlcJfx32H428GPd0dqITi3EttdClIrr7YH9E4nn0Bq+Ran94ArO8wU/lyufVcw==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
