name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform-security:
    runs-on: ubuntu-latest
    name: Run tfsec on Terraform files
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

  trivy-scan:
    runs-on: ubuntu-latest
    name: Trivy scan for Docker image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget rpm
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.64.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.64.1_Linux-64bit.deb

      - name: Scan Docker image
        run: trivy image nginx
